import{i as l,S as u}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();function p(s){const o="https://pixabay.com/api/",t=new URLSearchParams({key:"42959666-b225ac6c9c40b570269fe0b4e",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),i=`${o}?${t}`;return fetch(i).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function d(s){if(s.length==0)l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",progressBarColor:"#FFFFFF",icon:null,backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff"});else{const o=s.map(t=>`<li class="image-item">
          <a class="image-link" href="${t.largeImageURL}">
          <img class="image" src="${t.webformatURL}" alt="${t.tags}" />
          </a>
          <ul class="image-information-box">
          <li class="item-information"><p><span class="info-title">Likes</span></br>${t.likes}</p></li>
          <li class="item-information"><p><span class="info-title">Views</span></br>${t.views}</p></li>
          <li class="item-information"><p><span class="info-title">Comments</span></br>${t.comments}</p></li>
          <li class="item-information"><p><span class="info-title">Downloads</span></br>${t.downloads}</p></li>
          </ul>
          </li >`).join("");f.insertAdjacentHTML("beforeend",o),h.refresh()}}const c=document.querySelector(".search-form"),f=document.querySelector(".gallery"),h=new u(".gallery a",{captionsData:"alt",captionDelay:300}),m=document.querySelector(".loader");function g(){m.classList.remove("is-hidden")}function a(){m.classList.add("is-hidden")}c.addEventListener("submit",y);function y(s){s.preventDefault(),g(),f.innerHTML="";const o=s.target.elements.search.value.trim();o!==""?p(o).then(t=>{d(t.hits),a(),c.reset()}).catch(t=>{console.log(t),l.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),a()}):(l.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"}),a())}
//# sourceMappingURL=commonHelpers.js.map
