import{a as v,S as P,i as c}from"./assets/vendor-b2578120.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&n(g)}).observe(document,{childList:!0,subtree:!0});function r(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(o){if(o.ep)return;o.ep=!0;const s=r(o);fetch(o.href,s)}})();const M="42959666-b225ac6c9c40b570269fe0b4e",S="https://pixabay.com/api/";async function h(e,t,r){try{return(await v.get(S,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r}})).data}catch(n){throw console.error("Error fetching images:",n),n}}function y(e){if(e.length==0)iziToast.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",progressBarColor:"#FFFFFF",icon:null,backgroundColor:"#ef4040",titleColor:"#fff",messageColor:"#fff"});else{const t=e.map(r=>`<li class="image-item">
          <a class="image-link" href="${r.largeImageURL}">
          <img class="image" src="${r.webformatURL}" alt="${r.tags}" />
          </a>
          <ul class="image-information-box">
          <li class="item-information"><p><span class="info-title">Likes</span></br>${r.likes}</p></li>
          <li class="item-information"><p><span class="info-title">Views</span></br>${r.views}</p></li>
          <li class="item-information"><p><span class="info-title">Comments</span></br>${r.comments}</p></li>
          <li class="item-information"><p><span class="info-title">Downloads</span></br>${r.downloads}</p></li>
          </ul>
          </li >`).join("");a.insertAdjacentHTML("beforeend",t),a.insertAdjacentElement("beforeend",l),L.refresh()}}const q=document.querySelector(".search-form"),p=document.querySelector(".search-input"),a=document.querySelector(".gallery"),b=document.querySelector(".loader"),l=document.querySelector(".load-more-btn"),L=new P(".gallery a",{captionsData:"alt",captionDelay:300});L.refresh();m();u();let d="",i=1;const f=15;q.addEventListener("submit",C);async function C(e){if(e.preventDefault(),d=p.value.trim(),i=1,a.innerHTML="",d===""){c.error({title:"Error",message:"Please enter a search term.",position:"topRight"}),m();return}F(),E();try{const t=await h(d,i,f),r=t.totalHits;if(t.hits.length===0){a.innerHTML="",c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u();return}else y(t.hits),p.value="",x();f*i>=r&&(u(),w())}catch(t){console.error("Error fetching images:",t),c.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{m()}}l.addEventListener("click",async()=>{try{l&&(i+=1);const e=await h(d,i,f),t=e.totalHits;y(e.hits),E(),i*f>=t&&(u(),w());const r=a.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}catch(e){console.error("Error fetching more images:",e),c.error({title:"Error",message:`Error fetching more images: ${e}`})}finally{m()}});function E(){b.classList.remove("is-hidden")}function m(){b.classList.add("is-hidden")}function x(){l.classList.remove("is-hidden")}function u(){l.classList.add("is-hidden")}function F(){const e=document.querySelector(".end-message");e&&e.remove()}function w(){const e=document.createElement("p");e.style.display="flex",e.style.alignItems="center",e.style.justifyContent="center",e.style.margin="20px auto",e.classList.add("end-message"),e.textContent="We're sorry, but you've reached the end of search results.",a.insertAdjacentElement("beforeend",e)}
//# sourceMappingURL=commonHelpers.js.map
